
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programleftPLUSMINUSleftTIMESDIVIDEASSIGN CADENA DIVIDE ENTERO FUNCION ID MINUS PAREN_A PAREN_C PLUS PUNTO PUNTOYCOMA REAL TIMES TIPOprogram : stmt_liststmt_list : stmt_list statementstmt_list : statementstatement : declaracion PUNTOYCOMA\n| asignacion PUNTOYCOMA\n| lectura PUNTOYCOMA\n| escritura PUNTOYCOMAdeclaracion : ID TIPOasignacion : ID ASSIGN expresionlectura : ID ASSIGN FUNCION PUNTO TIPO PAREN_A PAREN_Cescritura : FUNCION PUNTO TIPO PAREN_A CADENA PAREN_Cescritura : FUNCION PUNTO TIPO PAREN_A expresion PAREN_Cexpresion : expresion PLUS  expresion\n| expresion MINUS expresion\n| expresion TIMES expresion\n| expresion DIVIDE expresionexpresion : PAREN_A expresion PAREN_Cexpresion : ENTERO\n| REALexpresion : CADENAexpresion : ID'
    
_lr_action_items = {'ID':([0,2,3,10,11,12,13,14,16,21,26,27,28,29,32,],[8,8,-3,-2,-4,-5,-6,-7,18,18,18,18,18,18,18,]),'FUNCION':([0,2,3,10,11,12,13,14,16,],[9,9,-3,-2,-4,-5,-6,-7,20,]),'$end':([1,2,3,10,11,12,13,14,],[0,-1,-3,-2,-4,-5,-6,-7,]),'PUNTOYCOMA':([4,5,6,7,15,18,19,22,23,24,33,34,35,36,38,42,43,44,],[11,12,13,14,-8,-21,-9,-18,-19,-20,-13,-14,-15,-16,-17,-11,-12,-10,]),'TIPO':([8,17,30,],[15,25,37,]),'ASSIGN':([8,],[16,]),'PUNTO':([9,20,],[17,30,]),'PAREN_A':([16,21,25,26,27,28,29,32,37,],[21,21,32,21,21,21,21,21,41,]),'ENTERO':([16,21,26,27,28,29,32,],[22,22,22,22,22,22,22,]),'REAL':([16,21,26,27,28,29,32,],[23,23,23,23,23,23,23,]),'CADENA':([16,21,26,27,28,29,32,],[24,24,24,24,24,24,39,]),'PLUS':([18,19,22,23,24,31,33,34,35,36,38,39,40,],[-21,26,-18,-19,-20,26,-13,-14,-15,-16,-17,-20,26,]),'MINUS':([18,19,22,23,24,31,33,34,35,36,38,39,40,],[-21,27,-18,-19,-20,27,-13,-14,-15,-16,-17,-20,27,]),'TIMES':([18,19,22,23,24,31,33,34,35,36,38,39,40,],[-21,28,-18,-19,-20,28,28,28,-15,-16,-17,-20,28,]),'DIVIDE':([18,19,22,23,24,31,33,34,35,36,38,39,40,],[-21,29,-18,-19,-20,29,29,29,-15,-16,-17,-20,29,]),'PAREN_C':([18,22,23,24,31,33,34,35,36,38,39,40,41,],[-21,-18,-19,-20,38,-13,-14,-15,-16,-17,42,43,44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmt_list':([0,],[2,]),'statement':([0,2,],[3,10,]),'declaracion':([0,2,],[4,4,]),'asignacion':([0,2,],[5,5,]),'lectura':([0,2,],[6,6,]),'escritura':([0,2,],[7,7,]),'expresion':([16,21,26,27,28,29,32,],[19,31,33,34,35,36,40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmt_list','program',1,'p_program','analizador_sintactico.py',83),
  ('stmt_list -> stmt_list statement','stmt_list',2,'p_stmt_list_multi','analizador_sintactico.py',88),
  ('stmt_list -> statement','stmt_list',1,'p_stmt_list_single','analizador_sintactico.py',93),
  ('statement -> declaracion PUNTOYCOMA','statement',2,'p_statement','analizador_sintactico.py',98),
  ('statement -> asignacion PUNTOYCOMA','statement',2,'p_statement','analizador_sintactico.py',99),
  ('statement -> lectura PUNTOYCOMA','statement',2,'p_statement','analizador_sintactico.py',100),
  ('statement -> escritura PUNTOYCOMA','statement',2,'p_statement','analizador_sintactico.py',101),
  ('declaracion -> ID TIPO','declaracion',2,'p_declaracion','analizador_sintactico.py',107),
  ('asignacion -> ID ASSIGN expresion','asignacion',3,'p_asignacion','analizador_sintactico.py',113),
  ('lectura -> ID ASSIGN FUNCION PUNTO TIPO PAREN_A PAREN_C','lectura',7,'p_lectura','analizador_sintactico.py',119),
  ('escritura -> FUNCION PUNTO TIPO PAREN_A CADENA PAREN_C','escritura',6,'p_escritura_cadena','analizador_sintactico.py',125),
  ('escritura -> FUNCION PUNTO TIPO PAREN_A expresion PAREN_C','escritura',6,'p_escritura_expr','analizador_sintactico.py',132),
  ('expresion -> expresion PLUS expresion','expresion',3,'p_expresion_binaria','analizador_sintactico.py',138),
  ('expresion -> expresion MINUS expresion','expresion',3,'p_expresion_binaria','analizador_sintactico.py',139),
  ('expresion -> expresion TIMES expresion','expresion',3,'p_expresion_binaria','analizador_sintactico.py',140),
  ('expresion -> expresion DIVIDE expresion','expresion',3,'p_expresion_binaria','analizador_sintactico.py',141),
  ('expresion -> PAREN_A expresion PAREN_C','expresion',3,'p_expresion_paren','analizador_sintactico.py',146),
  ('expresion -> ENTERO','expresion',1,'p_expresion_numero','analizador_sintactico.py',151),
  ('expresion -> REAL','expresion',1,'p_expresion_numero','analizador_sintactico.py',152),
  ('expresion -> CADENA','expresion',1,'p_expresion_cadena','analizador_sintactico.py',161),
  ('expresion -> ID','expresion',1,'p_expresion_id','analizador_sintactico.py',166),
]
